=== JulianMendezEdix/ad2_lenguajesDeMarcas/06_DTD_Biblioteca.dtd
<!-- BIBLIOTECA  -->

<!ELEMENT biblioteca (documentos)>


<!-- DOCUMENTOS  -->

<!ELEMENT documentos (libros, revistas, periodicos)>


<!-- LIBROS -->

<!ELEMENT libros (libro*)>
<!ELEMENT libro (titulo, sinopsis, indice)>

<!-- Definimos los atributos de cada libro-->
<!ATTLIST libro id ID #REQUIRED>
<!ATTLIST libro tipo_clase (novela|infantil|didactico) #REQUIRED>     
<!ATTLIST libro num_paginas CDATA #IMPLIED>    
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT sinopsis (#PCDATA)> 

<!-- El indice nos sirve para todos los documentos (libros, revistas y periodicos)-->
<!ELEMENT indice (capitulo*|seccion*|seccion_periodico*)>

<!ELEMENT capitulo (titulo, contenido)>
<!ATTLIST capitulo num_paginas CDATA #IMPLIED>
<!ELEMENT contenido (#PCDATA)>
<!ATTLIST contenido link CDATA #IMPLIED>


<!-- REVISTAS -->

<!ELEMENT revistas (revista*)>
<!ELEMENT revista (titulo, num_revista, indice)>
<!-- Definimos los atributos de cada revista-->
<!ATTLIST revista id ID #REQUIRED>
<!ATTLIST revista tipo_clase (informatica|corazon|coches|investigacion|otras) #REQUIRED>
<!ATTLIST revista num_paginas CDATA #REQUIRED>

<!ELEMENT num_revista (#PCDATA)>
<!ELEMENT seccion (contenido|articulo*)>
<!ATTLIST seccion num_paginas CDATA #IMPLIED>


<!-- PERIODICOS -->

<!ELEMENT periodicos (periodico*)>
<!ELEMENT periodico (indice)>
<!-- Definimos los atributos de cada PERIODICO-->
<!ATTLIST periodico id ID #REQUIRED>
<!ATTLIST periodico tipo_clase (nacional|internacional) #REQUIRED>
<!ATTLIST periodico fecha_publi CDATA #REQUIRED>

<!ELEMENT seccion_periodico (articulo*)>
<!ATTLIST seccion_periodico tipo_seccion (economica|opinion|deportes|nacional|internacional) #REQUIRED>
<!ELEMENT articulo (contenido)>
<!ATTLIST articulo autor CDATA #REQUIRED>

=== JulianMendezEdix/ad2_lenguajesDeMarcas/06_DTD_Biblioteca.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE biblioteca SYSTEM "06_DTD_Biblioteca.dtd">
<biblioteca>
    <documentos>
        <libros>
            <libro id="L0001" tipo_clase="novela" num_paginas="310">
                <titulo></titulo>
                <sinopsis></sinopsis>
                <indice>
                    <capitulo num_paginas="100">
                        <titulo></titulo>
                        <contenido link="https://www.w3schools.com/xml/xml_schema.asp">
                        </contenido>
                    </capitulo>
                    <capitulo num_paginas="100">
                        <titulo></titulo>
                        <contenido link="www.talycual.com">
                        </contenido>
                    </capitulo>
                    <capitulo num_paginas="100">
                        <titulo></titulo>
                        <contenido link="www.talycual.com">
                        </contenido>
                    </capitulo>
                </indice>
            </libro>
            <libro id="L0002" tipo_clase="infantil" num_paginas="310">
                <titulo></titulo>
                <sinopsis></sinopsis>
                <indice>
                    <capitulo num_paginas="100">
                        <titulo></titulo>
                        <contenido link="www.talycual.com">
                        </contenido>
                    </capitulo>
                    <capitulo num_paginas="100">
                        <titulo></titulo>
                        <contenido link="www.talycual.com">
                        </contenido>
                    </capitulo>
                    <capitulo num_paginas="100">
                        <titulo></titulo>
                        <contenido link="www.talycual.com">
                        </contenido>
                    </capitulo>
                </indice>
            </libro>
            <libro id="L0003" tipo_clase="didactico" num_paginas="310">
                <titulo></titulo>
                <sinopsis></sinopsis>
                <indice>
                    <capitulo num_paginas="100">
                        <titulo></titulo>
                        <contenido link="www.talycual.com">
                        </contenido>
                    </capitulo>
                    <capitulo num_paginas="100">
                        <titulo></titulo>
                        <contenido link="www.talycual.com">
                        </contenido>
                    </capitulo>
                    <capitulo num_paginas="100">
                        <titulo></titulo>
                        <contenido link="www.talycual.com">
                        </contenido>
                    </capitulo>
                </indice>
            </libro>
        </libros>
        <revistas>
            <revista id="R0001" tipo_clase="informatica" num_paginas="300">
                <titulo></titulo>
                <num_revista></num_revista>
                <indice>
                    <seccion num_paginas="100">                            
                        <contenido link="www.talycual.com">
                        </contenido>
                    </seccion>
                    <seccion num_paginas="100">                            
                        <contenido link="www.talycual.com">
                        </contenido>
                    </seccion>
                </indice>
            </revista>
            <revista id="R0002" tipo_clase="corazon" num_paginas="300">
                <titulo></titulo>
                <num_revista></num_revista>
                <indice>
                    <seccion num_paginas="100">                            
                        <contenido link="www.talycual.com">
                        </contenido>
                    </seccion>
                    <seccion num_paginas="100">                            
                        <contenido link="www.talycual.com">
                        </contenido>
                    </seccion>
                </indice>
            </revista>
            <revista id="R0003" tipo_clase="coches" num_paginas="300">
                <titulo></titulo>
                <num_revista></num_revista>
                <indice>
                    <seccion num_paginas="100">                            
                        <contenido link="www.talycual.com">
                        </contenido>
                    </seccion>
                    <seccion num_paginas="100">                            
                        <contenido link="www.talycual.com">
                        </contenido>
                    </seccion>
                </indice>
            </revista>
            <revista id="R0004" tipo_clase="investigacion" num_paginas="300">
                <titulo></titulo>
                <num_revista></num_revista>
                <indice>
                    <seccion num_paginas="100">                            
                        <contenido link="www.talycual.com">
                        </contenido>
                    </seccion>
                    <seccion num_paginas="100">                            
                        <contenido link="www.talycual.com">
                        </contenido>
                    </seccion>
                </indice>
            </revista>
            <revista id="R0005" tipo_clase="otras" num_paginas="300">
                <titulo></titulo>
                <num_revista></num_revista>
                <indice>
                        <seccion num_paginas="100">                            
                            <contenido link="www.talycual.com">
                            </contenido>
                        </seccion>
                        <seccion num_paginas="100">                            
                            <contenido link="www.talycual.com">
                            </contenido>
                        </seccion>
                </indice>
            </revista>
        </revistas>
        <periodicos>
            <periodico id="P0001" tipo_clase="nacional" fecha_publi="16/02/1990">
                <indice>
                    <seccion_periodico tipo_seccion="economica">  
                        <articulo autor="Strauss">
                            <contenido link="www.talycual.com">
                            </contenido>
                        </articulo> 
                        <articulo autor="Chopin">
                            <contenido link="www.talycual.com">
                            </contenido>
                        </articulo> 
                    </seccion_periodico>
                    <seccion_periodico tipo_seccion="opinion">  
                        <articulo autor="Mozart">
                            <contenido link="www.talycual.com">
                            </contenido>
                        </articulo> 
                        <articulo autor="Wagner">
                            <contenido link="www.talycual.com">
                            </contenido>
                        </articulo>                           
                    </seccion_periodico>
                    <seccion_periodico tipo_seccion="deportes">  
                        <articulo autor="Stravinsky">
                            <contenido link="www.talycual.com">
                            </contenido>
                        </articulo> 
                        <articulo autor="Rachmaninoff">
                            <contenido link="www.talycual.com">
                            </contenido>
                        </articulo>                           
                    </seccion_periodico>
                    <seccion_periodico tipo_seccion="nacional">  
                        <articulo autor="Bach">
                            <contenido link="www.talycual.com">
                            </contenido>
                        </articulo> 
                        <articulo autor="Mahler">
                            <contenido link="www.talycual.com">
                            </contenido>
                        </articulo>                           
                    </seccion_periodico>
                    <seccion_periodico tipo_seccion="internacional">  
                        <articulo autor="Granados">
                            <contenido link="www.talycual.com">
                            </contenido>
                        </articulo> 
                        <articulo autor="Albeniz">
                            <contenido link="www.talycual.com">
                            </contenido>
                        </articulo>                           
                    </seccion_periodico>
                </indice>
            </periodico>
            <periodico id="P0002" tipo_clase="internacional" fecha_publi="16/02/1985">
                <indice>
                    <seccion_periodico tipo_seccion="economica">  
                        <articulo autor="McCartney">
                            <contenido link="www.talycual.com">
                            </contenido>
                        </articulo> 
                        <articulo autor="Lennon">
                            <contenido link="www.talycual.com">
                            </contenido>
                        </articulo> 
                    </seccion_periodico>
                    <seccion_periodico tipo_seccion="opinion">  
                        <articulo autor="Cobain">
                            <contenido link="www.talycual.com">
                            </contenido>
                        </articulo> 
                        <articulo autor="Curtis">
                            <contenido link="www.talycual.com">
                            </contenido>
                        </articulo>                           
                    </seccion_periodico>
