=== JulianMendezEdix/ad2_lenguajesDeMarcas/06_XSD_Biblioteca.xsd
<?xml version="1.0"?> 
<schema xmlns="http://www.w3.org/2001/XMLSchema">
<element name="biblioteca">
    <complexType>
        <sequence>
            <element name="documentos">
                <complexType>
                    <sequence>
                        <element name="libros">
                            <complexType>
                                <sequence>
                                    <element name="libro" maxOccurs="unbounded">
                                        <complexType>
                                            <sequence>
                                                <element name="titulo" type="string"/>
                                                <element name="sinopsis" type="string"/>
                                                <element name="indice">
                                                    <complexType>
                                                        <sequence>
                                                            <element name="capitulo" maxOccurs="unbounded">
                                                                <complexType>
                                                                    <sequence>
                                                                        <element name="titulo" type="string"/>
                                                                        <element name="contenido">
                                                                            <complexType>
                                                                                <simpleContent>
                                                                                    <extension base="string">
                                                                                        <attribute name="link" type="string"/>   
                                                                                    </extension>
                                                                                </simpleContent>
                                                                            </complexType>
                                                                        </element>
                                                                    </sequence>
                                                                    <attribute name="num_paginas" type="integer"/>
                                                                </complexType>
                                                            </element>
                                                        </sequence>
                                                    </complexType>
                                                </element>
                                            </sequence>
                                            <attribute name="id" use="required">
                                                <simpleType>
                                                    <restriction base="string">
                                                        <pattern value="L\d{4}"/>
                                                    </restriction>
                                                </simpleType>
                                            </attribute>
                                            <attribute name="tipo_clase">
                                                <simpleType>
                                                    <restriction base="string">
                                                        <enumeration value="novela"/>
                                                        <enumeration value="infantil"/>
                                                        <enumeration value="didactico"/>
                                                    </restriction>
                                                </simpleType>
                                            </attribute>
                                            <attribute name="num_paginas" type="integer"/>
                                        </complexType>                
                                    </element>
                                </sequence>
                            </complexType>
                        </element>
                        <element name="revistas">
                            <complexType>
                                <sequence>
                                    <element name="revista" maxOccurs="unbounded">
                                        <complexType>
                                            <sequence>
                                                <element name="titulo" type="string"/>
                                                <element name="num_revista"/>
                                                <element name="indice">
                                                    <complexType>
                                                        <sequence>
                                                            <element name="seccion" maxOccurs="unbounded">
                                                                <complexType>
                                                                    <sequence>
                                                                        <element name="contenido">
                                                                            <complexType>
                                                                                <simpleContent>
                                                                                    <extension base="string">
                                                                                        <attribute name="link" type="string"/>   
                                                                                    </extension>
                                                                                </simpleContent>
                                                                            </complexType>
                                                                        </element>
                                                                    </sequence>
                                                                    <attribute name="num_paginas" type="integer"/>
                                                                </complexType>
                                                            </element>
                                                        </sequence>
                                                    </complexType>
                                                </element>
                                            </sequence>
                                            <attribute name="id" use="required">
                                                <simpleType>
                                                    <restriction base="string">
                                                        <pattern value="R\d{4}"/>
                                                    </restriction>
                                                </simpleType>
                                            </attribute>
                                            <attribute name="tipo_clase">
                                                <simpleType>
                                                    <restriction base="string">
                                                        <enumeration value="informatica"/>
                                                        <enumeration value="coches"/>
                                                        <enumeration value="corazon"/>
                                                        <enumeration value="investigacion"/>
                                                        <enumeration value="otras"/>                                                    </restriction>
                                                </simpleType>
                                            </attribute>
                                            <attribute name="num_paginas" type="integer"/>
                                        </complexType>
                                    </element>
                                </sequence>
                            </complexType>
                        </element>
                        <element name="periodicos">
                            <complexType>
                                <sequence>
                                    <element name="periodico" maxOccurs="unbounded">
                                        <complexType>
                                            <sequence>
                                                <element name="indice">
                                                    <complexType>
                                                        <sequence>
                                                            <element name="seccion_periodico" maxOccurs="unbounded">
                                                                <complexType>
                                                                    <sequence>
                                                                        <element name="articulo" maxOccurs="unbounded">
                                                                            <complexType>
                                                                                <sequence>
                                                                                    <element name="contenido">
                                                                                        <complexType>
                                                                                            <simpleContent>
                                                                                                <extension base="string">
                                                                                                    <attribute name="link" type="string"/>   
                                                                                                </extension>
                                                                                            </simpleContent>
                                                                                        </complexType>
                                                                                    </element>
                                                                                </sequence>
                                                                                <attribute name="autor" type="string"/>
                                                                            </complexType>
                                                                        </element>
                                                                    </sequence>
                                                                    <attribute name="tipo_seccion">
                                                                        <simpleType>
                                                                            <restriction base="string">
                                                                                <enumeration value="economica"/>
                                                                                <enumeration value="opinion"/>
                                                                                <enumeration value="deportes"/>
                                                                                <enumeration value="nacional"/>
                                                                                <enumeration value="internacional"/>                                                    </restriction>
                                                                        </simpleType>
                                                                    </attribute>
                                                                </complexType>
                                                            </element>
                                                        </sequence>
                                                    </complexType>
                                                </element>
                                            </sequence>
                                            <attribute name="id" use="required">
                                                <simpleType>
                                                    <restriction base="string">
                                                        <pattern value="P\d{4}"/>
                                                    </restriction>
                                                </simpleType>
                                            </attribute>
                                            <attribute name="tipo_clase">
                                                <simpleType>
                                                    <restriction base="string">
                                                        <enumeration value="internacional"/>
                                                        <enumeration value="nacional"/>                                                 
                                                    </restriction>
                                                </simpleType>
                                            </attribute>
                                            <attribute name="fecha_publi" type="date"/>
                                        </complexType>
                                    </element>
                                </sequence>
                            </complexType>
                        </element>
                    </sequence>
                </complexType>
            </element>
        </sequence>
    </complexType>
</element>
</schema>

=== JulianMendezEdix/ad2_lenguajesDeMarcas/06_XSD_Biblioteca.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:noNamespaceSchemaLocation= "06_XSD_Biblioteca.xsd">
    <documentos>
        <libros>
            <libro id="L0001" tipo_clase="novela" num_paginas="310">
                <titulo></titulo>
                <sinopsis></sinopsis>
                <indice>
                    <capitulo num_paginas="100">
                        <titulo></titulo>
                        <contenido link="https://www.google.es">
                        </contenido>
                    </capitulo>
                    <capitulo num_paginas="100">
                        <titulo></titulo>
                        <contenido link="https://www.google.es">
                        </contenido>
                    </capitulo>
                    <capitulo num_paginas="100">
                        <titulo></titulo>
                        <contenido link="https://www.google.es">
                        </contenido>
                    </capitulo>
                </indice>
            </libro>
            <libro id="L0002" tipo_clase="infantil" num_paginas="310">
                <titulo></titulo>
                <sinopsis></sinopsis>
                <indice>
                    <capitulo num_paginas="100">
                        <titulo></titulo>
                        <contenido link="https://www.google.es">
                        </contenido>
                    </capitulo>
                    <capitulo num_paginas="100">
                        <titulo></titulo>
                        <contenido link="https://www.google.es">
                        </contenido>
                    </capitulo>
                    <capitulo num_paginas="100">
                        <titulo></titulo>
                        <contenido link="https://www.google.es">
                        </contenido>
                    </capitulo>
                </indice>
            </libro>
            <libro id="L0003" tipo_clase="didactico" num_paginas="310">
                <titulo></titulo>
                <sinopsis></sinopsis>
                <indice>
                    <capitulo num_paginas="100">
                        <titulo></titulo>
                        <contenido link="https://www.google.es">
                        </contenido>
                    </capitulo>
                    <capitulo num_paginas="100">
                        <titulo></titulo>
                        <contenido link="https://www.google.es">
                        </contenido>
                    </capitulo>
                    <capitulo num_paginas="100">
                        <titulo></titulo>
                        <contenido link="https://www.google.es">
                        </contenido>
                    </capitulo>
                </indice>
            </libro>
        </libros>
        <revistas>
            <revista id="R0001" tipo_clase="informatica" num_paginas="300">
                <titulo></titulo>
                <num_revista></num_revista>
                <indice>
                    <seccion num_paginas="100">                            
                        <contenido link="https://www.google.es">
                        </contenido>
                    </seccion>
                    <seccion num_paginas="100">                            
                        <contenido link="https://www.google.es">
                        </contenido>
                    </seccion>
                </indice>
            </revista>
            <revista id="R0002" tipo_clase="corazon" num_paginas="300">
                <titulo></titulo>
                <num_revista></num_revista>
                <indice>
                    <seccion num_paginas="100">                            
                        <contenido link="https://www.google.es">
                        </contenido>
                    </seccion>
                    <seccion num_paginas="100">                            
                        <contenido link="https://www.google.es">
                        </contenido>
                    </seccion>
                </indice>
            </revista>
            <revista id="R0003" tipo_clase="coches" num_paginas="300">
                <titulo></titulo>
                <num_revista></num_revista>
                <indice>
                    <seccion num_paginas="100">                            
                        <contenido link="https://www.google.es">
                        </contenido>
                    </seccion>
                    <seccion num_paginas="100">                            
                        <contenido link="https://www.google.es">
                        </contenido>
                    </seccion>
                </indice>
            </revista>
            <revista id="R0004" tipo_clase="investigacion" num_paginas="300">
                <titulo></titulo>
                <num_revista></num_revista>
                <indice>
                    <seccion num_paginas="100">                            
                        <contenido link="https://www.google.es">
                        </contenido>
                    </seccion>
                    <seccion num_paginas="100">                            
                        <contenido link="https://www.google.es">
                        </contenido>
                    </seccion>
                </indice>
            </revista>
            <revista id="R0005" tipo_clase="otras" num_paginas="0">
                <titulo></titulo>
                <num_revista></num_revista>
                <indice>
                        <seccion num_paginas="100">                            
                            <contenido link="https://www.google.es">
                            </contenido>
                        </seccion>
                        <seccion num_paginas="100">                            
                            <contenido link="https://www.google.es">
                            </contenido>
                        </seccion>
                </indice>
            </revista>
        </revistas>
        <periodicos>
            <periodico id="P0001" tipo_clase="nacional" fecha_publi="1990-02-02">
                <indice>
                    <seccion_periodico tipo_seccion="economica">  
                        <articulo autor="Strauss">
                            <contenido link="https://www.google.es">
                            </contenido>
                        </articulo> 
                        <articulo autor="Chopin">
                            <contenido link="https://www.google.es">
                            </contenido>
                        </articulo> 
                    </seccion_periodico>
                    <seccion_periodico tipo_seccion="opinion">  
                        <articulo autor="Mozart">
                            <contenido link="https://www.google.es">
                            </contenido>
                        </articulo> 
                        <articulo autor="Wagner">
                            <contenido link="https://www.google.es">
                            </contenido>
                        </articulo>                           
                    </seccion_periodico>
                    <seccion_periodico tipo_seccion="deportes">  
                        <articulo autor="Stravinsky">
                            <contenido link="https://www.google.es">
                            </contenido>
                        </articulo> 
                        <articulo autor="Rachmaninoff">
                            <contenido link="https://www.google.es">
                            </contenido>
                        </articulo>                           
                    </seccion_periodico>
                    <seccion_periodico tipo_seccion="nacional">  
                        <articulo autor="Bach">
                            <contenido link="https://www.google.es">
                            </contenido>
                        </articulo> 
                        <articulo autor="Mahler">
                            <contenido link="https://www.google.es">
                            </contenido>
                        </articulo>                           
                    </seccion_periodico>
                    <seccion_periodico tipo_seccion="internacional">  
                        <articulo autor="Granados">
                            <contenido link="https://www.google.es">
                            </contenido>
                        </articulo> 
                        <articulo autor="Albeniz">
                            <contenido link="https://www.google.es">
                            </contenido>
                        </articulo>                           
                    </seccion_periodico>
                </indice>
            </periodico>
            <periodico id="P0002" tipo_clase="internacional" fecha_publi="1985-02-16">
                <indice>
                    <seccion_periodico tipo_seccion="economica">  
                        <articulo autor="McCartney">
                            <contenido link="https://www.google.es">
                            </contenido>
                        </articulo> 
                        <articulo autor="Lennon">
                            <contenido link="https://www.google.es">
                            </contenido>
                        </articulo> 
                    </seccion_periodico>
                    <seccion_periodico tipo_seccion="opinion">  
                        <articulo autor="Cobain">
                            <contenido link="https://www.google.es">
                            </contenido>
                        </articulo> 
                        <articulo autor="Curtis">
                            <contenido link="https://www.google.es">
